locale: ja-JP

log:
  enable: true
  path: tax.log
  
database:
  enable: false
  debug: false
  host: localhost
  # port: 3306
  database: takenomics
  # tablePrefix: ''
  user: root
  # password: ''

taxOnSavings:
  enable: true
  debug: false
  interval: 3600
  table:
  - min: 10000
    rate: 0.001
  - min: 1000000
    rate: 0.03

redstoneTax:
  enable: true
  debug: false
  interval: 900
  table:
  - min: 0
    rate: 0.1
  - min: 3600
    rate: 1.0
  - min: 18000
    rate: 10.0
  - min: 36000
    rate: 100.0
  taxExempt:
  - towncenter
  - owner_farm