locale: ja-JP

log:
  enable: true
  path: tax.log
  
database:
  enable: false
  debug: false
  host: localhost
  port: 3306
  database: takenomics
  tablePrefix: takenomics_
  user: root
  password: ''

taxOnSavings:
  enable: true
  debug: false
  interval: 3600
  table:
  - min: 10000
    rate: 0.001
  - min: 1000000
    rate: 0.03

redstoneTax:
  enable: true
  debug: false
  interval: 900
  table:
  - min: 0
    rate: 0.1
  - min: 3600
    rate: 1.0
  - min: 18000
    rate: 10.0
  - min: 36000
    rate: 100.0
  taxExempt: []

livestockTax:
  enable: true
  debug: false
  interval: 600
  untamedTable:
  - min: 3
    rate: 100.0
  - min: 10
    rate: 500.0
  - min: 20
    rate: 2500.0
  tamedTable:
  - min: 3
    rate: 1000.0
  - min: 5
    rate: 5000.0
  - min: 10
    rate: 50000.0
  taxExempt: []

hopperTax:
  enable: true
  debug: false
  interval: 600
  table:
  - min: 16
    rate: 100.0
  - min: 24
    rate: 1000.0
  - min: 32
    rate: 10000.0
  - min: 40
    rate: 100000.0
