name: Takenomics
main: jp.dip.myuminecraft.takenomics.Takenomics
version: 0.0.3
depend: [Vault, WorldGuard]
softdepend: [ChestShop]
commands:
  takenomics:
    usage: /takenomics <subcommand> ...
    permission: takenomics.command
