name: Takenomics
main: jp.dip.myuminecraft.takenomics.Takenomics
version: "${project.version}"
depend: [Vault, WorldGuard, Essentials, TakeCore]
softdepend: [ChestShop]
commands:
  takenomics:
    usage: /takenomics <subcommand> ...
